### ISSUE TITLE
Alternative way of connecting stream to React function components

### ISSUE THREAD

**Issue by alexsherman** [foxdonut/meiosis#106]
Hi foxdonut,

Thanks for your work on meiosis! I wanted to suggest a somewhat-opinionated alternative to how to hook up the state stream to the view in React which differs slightly from the setup and the docs. The following, from the setup, is very useful as a template for getting things set up initially:

```javascript
export default ({ React, Root }) => ({ states, update, actions }) => {
  const [init, setInit] = React.useState(false);
  const [state, setState] = React.useState(states());

  if (!init) {
    setInit(true);
    states.map(setState);
  }

  return React.createElement(Root, { state, update, actions });
};
```

The main issues I encountered with the above in a larger codebase were the inconvenience of passing state/update/actions as props and, more importantly, the fact that above re-renders the entire tree on every state update. I've read your [post on preventing re-renders](https://meiosis.js.org/docs/preventing-re-renders.html). I agree with avoiding focusing on performance too early, but these problems do come up, so it's nice to have a way to deal with it if it does. I thought that your suggested solution with `shouldComponentUpdate` and an id per component was useful, and this alternative is sort of like that but for a hooks + function component workflow. 

```javascript
export const StatesContext = createContext;

/*
* sliceFn is a pure fn that takes the current state object as a param
* and returns a slice of that state to which a component wishes to subscribe.
*/
export const useStateSlice = (sliceFn) => {
    const states = useContext(StatesContext);
    const stateSlice = sliceFn(states());
    const [slice, setSlice] = useState(stateSlice);
  
    // You can do any sort of comparison you want to decide when to rerender - id check, some deep equals, etc.
    // If you wanted to the hook to be more flexible, could allow passing a custom
    // comparison function, kind of similar to shouldComponentUpdate 
    const changed = (a, b) => JSON.stringify(a) !== JSON.stringify(b);

    useEffect(() => {
        let prevSlice = slice;

        const slices = states.map(newState => {
            const newSlice = sliceFn(newState);
            
            if (changed(prevSlice, newSlice) {
                prevSlice = newSlice;
                setSlice(newSlice);
            }
        });

        return () => slices.end(true);

    }, []);

    return slice;
};

//Top Level
export default ({  Root }) => ({ states, update, actions }) => {
    return <StatesContext.Provider value={states}>
        <Root update={update} actions={actions} />
    </StatesContext.Provider>
};

// Some deeply nested component which only needs a tiny bit of the state
const StatusIndicator = (props) => {
    const status = useStateSlice(state => state.status);
    
    return <div>{status}</div>
};
```

The general idea is to prevent any unnecessary re-rendering by allowing each component which needs some piece of state to create a stream which takes a slice of the current state (kind of like Redux `mapStateToProps`) and compares it to the previous slice, updating the component's local state if there has been a change. It's very convenient to use in components that perhaps previously didn't need any state and then require it later. The use of React's context isn't strictly necessary here, as long as the hook has a reference to the state stream.

Just wanted to put this out there, not sure if there was a better place. Maybe this will help someone googling for help with these patterns later on.

**Comment by foxdonut** [comment]
@alexsherman very nice to hear that Meiosis is useful!

I haven't worked with React much lately, so I'm a bit out of practice when it comes to hooks and context.

Your approach looks interesting! I'll have to experiment with it. One thing, would you do just a little bit of refactoring so that how to determine what has changed is not hardcoded?

```javascript
const changed = (a, b) => JSON.stringify(a) !== JSON.stringify(b);
```

I figure the function could be passed in as a parameter.

By the way, if no mutation occurs, would this work?

```javascript
const changed = (a, b) => a !== b;
```

Let me know if you have more thoughts on this. As I said I'd like to experiment with it and perhaps integrate it into the docs and `meiosis-setup`.

Many thanks!

**Comment by foxdonut** [comment]
This approach is interesting indeed. However I think there are just too many variations depending on each application's requirements, to be included in meiosis-setup. You can still use meiosis-setup to set up Meiosis itself, and then use the approach described by @alexsherman above to wire up React. Setting this part up yourself gives you all the liberty to adjust to your specific needs. Please also see my comment above to make change detection more flexible. Thanks @alexsherman !
