### ISSUE TITLE
Question on initialRoute

### ISSUE THREAD

**Issue by lesar** [foxdonut/meiosis#107]
I'm new to Meiosis and have some problem getting the initialRoute work.  
I'm using:  
    "meiosis-routing": "^3.0.0",  
    "meiosis-setup": "^5.1.2",  

My configuration:  

```javascript
import { createRouteSegments, routeTransition } from 'meiosis-routing/state'
import createRouteMatcher from 'feather-route-matcher'
import { createFeatherRouter } from 'meiosis-routing/router-helper'

export const Route = createRouteSegments([
  'Home'
  , 'Contatti'
  , 'NotFound'
])

export const routeConfig = {
  Home: '/'
  , Contatti: '/contatti'
}

export const navTo = route => ({ nextRoute: () => Array.isArray(route) ? route : [route] })

export const routeService = state => ({
  routeTransition: () => routeTransition(state.route, state.nextRoute)
  , route: state.nextRoute
})


// ...

export const router = createFeatherRouter({
  createRouteMatcher
  , routeConfig
  , defaultRoute: [Route.NotFound()]
  // , getPath: function () { return document.location.pathname }
})

```
If I open in browser a url:  
https://mysite.com  
I get the right  Route.Home(), but if I open this url:  
https://mysite.com/contatti  
initialRoute is **not set** to Route.Contatti() but stay on Route.Home().  

I see in createFeatherRouter code the line [317](https://github.com/foxdonut/meiosis/blob/ac4d09a513ae77766a2a3bbaa22ebf3f02b64503/helpers/routing/src/router-helper/index.ts#L317):
```javascript
  const initialRoute = parsePath ? parsePath(getPath()) : undefined;
```
have this line to get url path from browser url?  

After router creation if I console.log(router.initialRoute) I get:  
```json
router.initialRoute
[
  {
    "id": "Home",
    "params": {}
  }
]
```
but I think that it have to be:  

```json
router.initialRoute
[
  {
    "id": "Contatti",
    "params": {}
  }
]
```

My app config is:  
```javascript
const app = {
  initial: Object.assign(
    {}
    , navTo(router.initialRoute)
    , home.initial
    , contatti.initial
  )
  , Actions: function (update) {
    return Object.assign(
      { navigateTo: route => update(navTo(route)) }
      , home.Actions(update)
      , contatti.Actions(update)
    )
  }
  , services: [routeService]
  , effects: update => []
}

```
home.initial and contatti.initial have not navigation function and 
      , home.Actions(update)  
      , contatti.Actions(update)  
are empty  

Have I not understanding the right Meiosis configuration?  
Is a bug?

best regards,
Leonardo

**Comment by foxdonut** [comment]
@lesar 

Hi Leonardo,

The router uses the hash for routes, so please try instead:

https://mysite.com#/contatti

Hope that helps!

**Comment by lesar** [comment]
This Is a problem: URL have semantic rule on web and change a multi Page site to single Page Is not possibile in my project.  
There Is a way to make router work in multiple URL?

Best regards,
Leonardo

**Comment by foxdonut** [comment]
`meiosis-routing` only supports hash mode.
I am working on a router setup that also supports history mode, but it is not ready yet.

**Comment by lesar** [comment]
Ok, 
Thank you.
I Will use Meiosis without routing

**Comment by foxdonut** [comment]
@lesar This is work in progress but posting it here in case it is useful to you.

https://github.com/foxdonut/meiosis/tree/master/docs/code/router-setup

These are current `router-setup` examples. You will find history-mode in subfolder.

Cheers.

**Comment by lesar** [comment]
thanks @foxdonut but I have change my mind:  
my app is a node isomorphic so I think I can try to move to spa and use router in hash mode and try to achieve a good index by search engine too.  

best regards,  
Leonardo

**Comment by lesar** [comment]
I have some news @foxdonut.  

(I'm not very constant and have try to make your standard route work on standard multiple url instead a single page and url prefixed by `#`  )

And all seam to work well.  

this is my router creation:  
```javascript
const router = createFeatherRouter({
  createRouteMatcher
  , routeConfig
  , defaultRoute: [Route.NotFoundView()]
  , prefix: ''                                                 // <---------------
  , getPath: function () { return document.location.pathname } // <---------------
})
```
I have changed prefix to '' and `getPath` to use `document.location.pathname`  

My project is a prototype and this is my router config:  
```javascript
export const routeConfig = {
  HomeView: '/'
  , ContattiView: ['/contatti', { ContattiSubView: '/:id' }]
}
```
Now ContattiView show a subpage '/contatti' and 
inside it I have put this hyperscript code:  
```javascript
            div([
              a({ href: router.toPath(routing.childRoute(Route.ContattiSubView({ id: 3 }))) }, [
                span('Go to sub contatti 3')
              ])
            ])
            , div([
              a({ href: router.toPath(routing.childRoute(Route.ContattiSubView({ id: 4 }))) }, [
                span('Go to sub contatti 4')
              ])
            ])
// ....................
            routing.childSegment.id === 'ContattiSubView' && (
              ContattiSubView({ states, update, actions, router, routing: routing.next(), viewsMap })
            )
```
Now by click on a link I can go on:  
`www.mysite.com/contatti/3`  

and this enable ContattiSubView that show his detail data inside ContattiView  

at every click on url the app call server to get new dehydratate page and on show clientside the page is hydrate and all work ok.  

In this manner seams that Meiosis routing can work on standard multi-page site and not only on single page.  

Have I misunderstand something?  
There was some downside I have not see yet?  
I'm interesting on some opinion on this way to use Meiosis routing, let me know.

best regards,  
Leonardo

**Comment by foxdonut** [comment]
@lesar That looks very good, indeed Meiosis routing was designed so that you could configure behaviour.

Thank you for writing back on how you are using it, great to hear!
