### ISSUE TITLE
react context - some clues?

### ISSUE THREAD

**Issue by amelon** [foxdonut/meiosis#13]
Hello,
I like your work and I try to map some part of my project with meiosis pattern.
I'm using a lot redux and redux-saga with some pro and many cons.
I like the way redux and react-redux use context to propagate store accross component hierarchy.
I'm trying to figure out how to do the same thing with meiosis but I'm stuck.

Do you have any clues or work in progress?

thanks

**Comment by foxdonut** [comment]
Hi @amelon 

Thank you for your kind words, I am happy to hear that you are finding Meiosis useful.

For the equivalent of React Context, indeed I plan to do a writeup.

In the meantime, you can look at the sample code [here in the Meiosis Wiki](http://meiosis.js.org/wiki/05-Lifecycle-and-other-Techniques-C-React-Context.html)

Essentially you designate a property of your choice (it is `context` in the example) and adapt the `nest` utility function to always pass down the content in the `view` function.
Then you can continue to call `view(model)` as before, and your components will always have access to `context` regardless of where they are nested.

I hope that helps, let me know if you have any questions.

**Comment by amelon** [comment]
@foxdonut thanks.

I've read your exemple, it is simple.
I will try to make some tests.

take care with this exemple as it mutates context and it can be dangerous.
If you try to keep first view with fix theme, it will impact the second one.

```
  var view = function(model) {
    return (<div>
      {water.view(Object.assign(model, { context: { theme: "light" } }))}
      {air.view(model)}
    </div>);
  };
```

But I don't really understand why the "theme" button is not impacted

**Comment by foxdonut** [comment]
@amelon you are correct, this needs to use instead:

```js
Object.assign({}, model, { context: { theme: "light" } })
```

Thank you for spotting that, I have made the change.
