### ISSUE TITLE
react performance impact?

### ISSUE THREAD

**Issue by ryuken** [foxdonut/meiosis#14]
Hi is there a performance impact with calling ReactDOM.render again upon changes in the model?
Does it work the same as a normal re-render?

**Comment by foxdonut** [comment]
Hi @ryuken 

In short, most often there is no significant performance impact when re-rendering upon model changes.

Please see the following for more detailed discussion and examples:

- [Medium article regarding performance concerns](https://medium.com/@foxdonut00/addressing-performance-concerns-in-meiosis-789466cfed6b)
- [Preventing Re-renders on the Meiosis Wiki](http://meiosis.js.org/wiki/05-Lifecycle-and-other-Techniques-B-Preventing-Rerenders.html)
