### ISSUE TITLE
Can meiosis pattern have separation model and view ?

### ISSUE THREAD

**Issue by meepeek** [foxdonut/meiosis#18]
Can I have all models and actions in one place before assign to components ? The example I saw had only model and view contained in a component.

I want to make a develop environment where I can call actions manually. This way I can test all actions before coding the UI. Could you give me an example ?

**Comment by foxdonut** [comment]
Hi @meepeek 

Certainly, you can have models and actions separately. They are just plain objects and functions, after all.

[See this for an example of separate actions that you can call manually](https://github.com/foxdonut/meiosis-examples/blob/master/examples/sandbox/react-app/src/App.js#L6).

Full example: https://github.com/foxdonut/meiosis-examples/tree/master/examples/sandbox/react-app
