### ISSUE TITLE
Can I use existing react component e.g. @material-ui/core with the pattern ?

### ISSUE THREAD

**Issue by meepeek** [foxdonut/meiosis#19]
I create react app with create-react-app command line. How can I integrate meiosis with that ?

**Comment by meepeek** [comment]
Seems it can but I could not understand the example well.

http://meiosis.js.org/wiki/05-Techniques-and-Strategies-A-Using-Lifecycle.html

**Comment by foxdonut** [comment]
Hi @meepeek 

See this example, created with `create-react-app`, and Meiosis integration. Also has a component from `@materiau-ui/core`. I hope this helps.

https://github.com/foxdonut/meiosis-examples/tree/master/examples/sandbox/react-app
