### ISSUE TITLE
Meiosis with React-Native

### ISSUE THREAD

**Issue by foxdonut** [foxdonut/meiosis#2]
Meiosis needs to account for the absence of `window` under React-Native.

Thanks to @mnichols for reporting this issue.

**Comment by mnichols** [comment]
@foxdonut i confirmed `v0.8.1` in environmen without `window` (eg react-native). should make the lib much more portable now (like for Electron apps, etc)....

**Comment by foxdonut** [comment]
Thank you @mnichols !

**Comment by qur2** [comment]
Hi,

I am also interested in this setup. I understand that I cannot use a renderer because I don't control the actual render in `react-native`. How does it work in this case?

Thanks.

**Comment by foxdonut** [comment]
@qur2 [here](https://gist.github.com/foxdonut/f70f71a99d9e5f9000882e24f9eb4336) is a Meiosis + React Native simple counter example. Note that `MeiosisReactNative` is inline but really would be in a library that you import, similarly to a renderer. I tried this on Mac+iOS simulator (iPhone 6).

**Comment by mnichols** [comment]
@qur2 you probably will want some form of Navigator and it took me a bit to grok how a Navigator implementation might tie in. 
 I got it integrated with [ex-navigation](https://github.com/exponentjs/ex-navigation) nicely by having a `navigation` meiosis component that, among other things, allows me to pass route actions thru propose->model->state to transform to a proper route (or not). Ex-navigation uses redux internally so i can control it with a reference to the store.
The renderer is given a bit of intelligence to Do The Right Thing with whatever navigation implementation you are using  or invokes the component function by default.

Here is an example of what that might look like with ex-navigation:
```
import {
    InteractionManager
} from 'react-native'

import {
    NavigationActions
} from '@exponent/ex-navigation'

export default function renderer({
    store,
    router
}) {
    let currentRoute = false
    /**
     * https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationActions.js
     * https://facebook.github.io/react-native/docs/interactionmanager.html
     * **/
    return function renderer(state, component) {
        if(!state.route) {
            return component(state)
        }
        let targetRoute = router.getRoute(state.route.$name, state)
        let id = store.getState().navigation.currentNavigatorUID
        if(currentRoute && currentRoute.routeName === state.route.$name) {
            currentRoute = targetRoute
            return InteractionManager.runAfterInteractions(() => {
                return store.dispatch(NavigationActions.updateCurrentRouteParams(id, state))
            })
        }
        currentRoute = targetRoute
        return store.dispatch(NavigationActions.push(id, targetRoute))
    }
}
```

**Comment by foxdonut** [comment]
Fixed in v0.8.1.

**Comment by qur2** [comment]
Hi,

I just had a look into your gist and it works great, thanks!

**Comment by qur2** [comment]
@foxdonut, I have a question about the meiosis - react-native bindings you gisted: am I correct to think that the whole component tree under the root meiosis component will be rerendered? If that's correct, I guess that having optimized `shouldComponentUpdate` is a must?

**Comment by foxdonut** [comment]
@qur2 I believe you are correct!
