### ISSUE TITLE
Can I create a component in meiosis pattern then use as a component in React component ?

### ISSUE THREAD

**Issue by meepeek** [foxdonut/meiosis#20]

**Comment by foxdonut** [comment]
Hi @meepeek 

I created an example for you with a React component and a Meiosis component (i.e. plain objects and functions), I hope that is helpful.

https://github.com/foxdonut/meiosis-examples/tree/master/examples/sandbox/react-app

**Comment by meepeek** [comment]
@foxdonut Thanks for React examples you provided. I am learning the sample.

**Comment by meepeek** [comment]
I have created a corresponding example which compact meiosis pattern into a class as follow

https://github.com/meepeek/meiosis-react-example
