### ISSUE TITLE
Does animation e.g. react-motion, pose works with meiosis ?

### ISSUE THREAD

**Issue by meepeek** [foxdonut/meiosis#21]

**Comment by foxdonut** [comment]
@meepeek yes, [here is an example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiAwAHUcIB8LAPQdOkkAF8K6bLkQEAVgip0GTYnhkzuAYQBOMDsUTcSxUXEQmA5hGKEArgCN8dLBlqQiZXKFovGSsMamIAWixaYgh6GWIrGBksDDhGCzkYRLgCxIAGOLgILFFYOPSMNErk+kE0Vv1c7mBuAFkklLQKbjhRCwg0V24lbn5uACUYGOI+5ra1juJuABFC2hnuL1E2DEYZyS7W7m4N+wa2WD6vOBgt2gB3NH2ACgBKM4vPlcDkcTjAvok2DAoP9gJcgVcIVD8LRREx9gBCRFQZGotbwq5WYheCyfLFwq5KH5wpStOGE4mfWGAq6cCAwN52LFncncL48q7sLiSflAlg+LzEYj0bj0R7PV4ffjAQh3B4ReXvNBKSQAFVorjCMFk4sl9GFePxApWA2GxAAnrAlcAAB52EZjCbg2iQ7EotEAfm4ABZSqVuHZSj8lNqRfDgF8XZTuczLUCTNdCNA2FZPhA4NwMNcMFAoD4YgBrbhvTPBYaECJQNgF6jUGCiTaeGDXYk5zacYteLu0MCx-HpgAGuQdMHHo-hgp41CgOTgADl1EIQJCylI5-iF9dl3A1xvhNvaOUfOFqOXhLbp0695aAOowHzljw6iwNOBgWgWLA7GEepGmXRgAGY2D5EBuAAam4Z04O4YRRGdIZSnQqlKCffEQN-f9AOQkA8LAmBIOgpDEPglC0O4DC6KwigcIpaYZHNVN9zkIU9xpFN5xka0zRFWR5HYoEqUBXjePaehOkOY5TlmMAoDtNh8FyaIsF+GTGk2LF8yUlS1LgagGi+L5aLAP5+HOMALJ+IZuj9NA7DAYtnimIZ5NBCSbnPfYdkSL5vMYCT9PwbJRC9H1-gWJYtgAeR6fAc0hCwvnPfBWXZaKoQcgtxB+CTKBoWhqmgGALDwMsfChErnlgWIBgQTRwIATkQUplFUEBMBwPB-GPEr9EYZhNG4fBzzDJl4R8f80rib8OCeOwg1QgBuHkyxvVwLAiNA2DiOhwgsOwLFcHwvgAJhDIYbvoq7wKun5NpTURaCaAYzqhE4uBgV74Wyc7xjsABWVDuHAiGAEZSg2nk3j4TxVtBuHnQBoEQggVwSDBtHXt4ybdkva9KxmoF3s++g7AwHw4FoKAJX+hGkcIPH4ZTLGcdsbhUY52b5sqxaMGW5xg35oFtvLXb9sO47-zOi6vmh8D6OhgAOaGhmhtr1Ze1peKueqoRgJrZLwaHQc65QAF0qCgcZyxa1BevUPBoliInOChFEcAYfAdBK4lyE0BwnBcGQvDQURpf8MqokWWJI6wNgE6WL2fdEP3iAD3RiLtVE8BMsZ226tR+s0D34jYMqM-CLPDFzoOLBDkAw+cEwo5j1w48CKu4hrwIvBTtPYgH2vIW9+vs6bqh7ULzRi4gUuVHLjQQH7xJVlnkBg7wduI672OAlH+It4GAABUp8FB-ArpkcUs1PhJ+noHf5-XpeV56vr1+U1Sd571DpKcOndo7H3jv-NgV8774HVjIKB78C6f2oCXIwSg7auwriAHoMAUiVHzPBOKsReivzQMoIAA).
