### ISSUE TITLE
How to integrate it into a redux app

### ISSUE THREAD

**Issue by Agamennon** [foxdonut/meiosis#25]
Great stuff!, i was wondering it this pattern will be hard to integrate inside an existing redux app, how do i use that pattern only on part of the app on a specific route?

**Comment by foxdonut** [comment]
@Agamennon good question, you should be able to integrate it gradually
Thank you for your kind words!

**Comment by Agamennon** [comment]
About that... redux uses react-redux to control rendering, if i try to render meiosis style inside a react-redux component it will fail, any ideas?

**Comment by foxdonut** [comment]
Perhaps try to phase out a react-redux component and integrate Meiosis just for that part, and see if you can apply it gradually to more areas?

**Comment by Agamennon** [comment]
Got it to work, router was messing some stuff up, again great stuff!
