### ISSUE TITLE
About React Hooks and meiosis state

### ISSUE THREAD

**Issue by aislanmaia** [foxdonut/meiosis#29]
Now that we have React Hooks, the usage with meiosis pattern is obsolete?

How can I make use of meiosis + react hooks to get a better state management in general?

**Comment by foxdonut** [comment]
hi @aislanmaia 

> Now that we have React Hooks, the usage with meiosis pattern is obsolete?

No, not at all.

First, React Hooks isn't as powerful a state management system as Meiosis.

Second, Hooks are specific to React, and specific version X+ of React. Meiosis is much more flexible and can be used with Preact, Mithril, lit-html, and other view libraries.

> How can I make use of meiosis + react hooks to get a better state management in general?

I haven't experimented with that idea, but if you get a chance to, please share your findings. Thanks!
