### ISSUE TITLE
Brilliant!

### ISSUE THREAD

**Issue by smuemd** [foxdonut/meiosis#31]
https://github.com/foxdonut/meiosis/blob/e38b896afe72057ba88e9df767a3a5c5f9ddf276/helpers/common/setup.js#L37-L41

This solves a real headache!

**Comment by foxdonut** [comment]
@smuemd thanks!

I will change to named parameters, i.e. from:

```javascript
export const setup = (stream, accumulator, acceptor, app) => ...
```

to:

```javascript
export const setup = ({ stream, accumulator, acceptor, app }) => ...
```

Also I'm debating making `acceptor` optional, for when you don't have any `acceptors` in `app`.

Any thoughts and suggestions are welcome!

**Comment by smuemd** [comment]
> Also I'm debating making acceptor optional, for when you don't have any acceptors in app.

a good idea

Maybe also worth debating could be to rename `app.actions` to `app.Actions`, since it works a bit like a constructor and you have a name collision down the line, when passing bufferdUpdate

**Comment by foxdonut** [comment]
> Maybe also worth debating could be to rename app.actions to app.Actions, since it works a bit like a constructor and you have a name collision down the line, when passing bufferdUpdate

Great idea, thank you :+1:

**Comment by smuemd** [comment]
I really like this a lot.

Being able to call multiple updates in services is very liberating.

The setup script makes the pattern feel a bit more library like. But at the same time, it becomes a lot more approachable I think.

For consistency, I guess I'd also capitalize initial like so:

```js
function setup ({ stream, accumulator, acceptor, app }) {
  app = app || {}

  const {
    Initial = () => ({}),
    Actions = () => ({}),
    acceptors = [],
    services = []
  } = app

/* ... */

}
```

**Comment by foxdonut** [comment]
Really happy to hear your positive feedback, it means a lot and I appreciate it.

I also agree that `Initial` makes this more consistent, I have made the change.

Thank you @smuemd !
