### ISSUE TITLE
Error on auth redirect

### ISSUE THREAD

**Issue by smuemd** [foxdonut/meiosis#33]
this is causing an error for me, because `state.login` is still `null` when the login view renders after redirect from the settings page. (only happens on redirect)

Can you reproduce this?

Might be related to the combinator optimisations in the setup script. Not sure, though

https://github.com/foxdonut/meiosis/blob/8e0b9082ddd6b832596886e68eb2d54df822caf4/docs/code/using-a-router/navigation/src/login/view.jsx#L20

**Comment by foxdonut** [comment]
You're right, I got a bit overzealous in my optimisations. Will fix.

**Comment by smuemd** [comment]
👍works!
