### ISSUE TITLE
Convert to Mergerino

### ISSUE THREAD

**Issue by fivitti** [foxdonut/meiosis#36]
Could you explain why do you convert from Patchinko to Mergerino?
Has Patchinko any important disadvantages to avoid using it in Meiosis?

**Comment by foxdonut** [comment]
@fivitti converted to Mergerino because it is simpler to use (less need to import and use `O(...)` and easier for newcomers.

But there is nothing wrong with Patchinko, if you are using it you can continue for sure.

**Comment by fivitti** [comment]
@foxdonut  Thanks for your answer! Mergerino looks very interesting and is really simpler than Patchinko. I noticed that it is more Typescript-friendly too.
