### ISSUE TITLE
View statics need to be hoisted onto returned func

### ISSUE THREAD

**Issue by mnichols** [foxdonut/meiosis#4]
Statics/function attributes need to be hoisted onto the returned function from `createComponent` so that HOC composition doesnt get buried.
For example, if you have a React component that is like:
```
function MyView(props) {
   return <div>me</div>
}
MyView.route = { styles: {... }}
export default MyView
```
The `route` static is lost (and inaccessible) because it is wrapped by the `createComponent` function. ([here](https://github.com/foxdonut/meiosis/blob/master/src/meiosis.ts#L105)).
In my opinion the composition of HOC by meiosis is an implementation detail that should be hidden, so statics should be hoisted...something like https://github.com/mridgway/hoist-non-react-statics.

Thots?

**Comment by foxdonut** [comment]
The new version of Meiosis gives you a lot more flexibility to decide what parameters to pass to your functions.
