### ISSUE TITLE
examples with react-hook (or solidjs state)

### ISSUE THREAD

**Issue by fradav** [foxdonut/meiosis#56]
How easy do you think it is to come with meiosis examples using hooks functions from react or [solidjs state manager](https://github.com/ryansolid/solid#solid-state) ?

**Comment by foxdonut** [comment]
Hi @fradav 

Thank you for your interest in Meiosis!

The React examples already use hooks. For example: [setup example code](https://github.com/foxdonut/meiosis-examples/blob/master/examples/setup/react/src/app/index.jsx#L26) - [example running here](http://meiosis.js.org/examples/setup/react/index.html)

I haven't tried solid.js, but it would probably be the same or similar approach.

**Comment by fradav** [comment]
Sorry I missed that. The todo example uses the old api, though. Solid.js should be interesting, there is subtilties I'm not sure I understand

**Comment by foxdonut** [comment]
Good catch, thanks for spotting that. I will update it.

**Comment by foxdonut** [comment]
I've updated the todo-list example to stop using the old React API.
