### ISSUE TITLE
Tutorial feedback

### ISSUE THREAD

**Issue by gilbert** [foxdonut/meiosis#7]
Congrats on releasing the new tutorial! The following is my feedback as I read through it. I've written a lot of educational material for programmers (beginners, specifically), so I hope to be of some help.

### 01 - Hello World

- The virtual dom concept is introduced very lightly, which is ok for those already familiar with the concept. I suggest linking to a resource that explains it for the uninformed.
- Great idea on starting with a simple example. I suggest [merging the js into the html file](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ArAGhAZ3ggxgC7xTIgCGADpQHQAWhYsIWAZhAtsgNqgB25MIiQVq9Rsyz4A9n2JyyAHigQAbgAJoAXgA6oynoB8igPQrVhnX0XZ8AJwiVClvuvUmAVAHNY0gEbksOpgHiZWbqrkdup48EJy6lrqUNL4AK7xhDRe8IQAogiZAEIAngCSUAAUelQGIACUANzh6pHRqilgicHVIHQAjHoY6noAEni+wwDu0nawUHpNLWA0dvB8UPB2lbGZwx3SYEvWJrYOTi4sOLFEELJcIihIAAwgAL4Y-ILC+jT42FwpLJ5IQyH5pFASsM-GlCIRZOpgC1WMCALSsQQcEpIdTYch8bCo3AOVjNVzqFFyIkQABe8Bx-TWYDJbysMLhsmhsPhfBosAgXgYiJa6Ts2FmOMo0ggci2ZLclHIMBlXhxACZKAAPdQADi16g12r1mvl6hkvjsOIAxGh0GgoABOU0BfAAay8dmkaQ2qPNEvUVtYQeDztmm0t6n6+vF-KgAdtaHtTuWUS8MpxABYtSy2dzZEg6NJVFtheSXe7Pd6oL7pBbrfAG42c3x2TyaFAoq7S25yx6vT6-RGbXbHabB9bgyGrKyW3neR27K6C0WS0iy+Q3X2qzW6wGUPu0Kxk3wZzRiGBKFtyIQ0mtu8FUzLUeCOWB1c9s9P3gBdLD8viug8vAgAIQhkJAhB0A4kggLezAiAwhCUNgSAmCY3qUO6fyHCYEFQRwAAC-Q0MRABsVyECUl5kGcjigm835vEAA) to make it even simpler to grasp (I also added a `vdom` variable to be clear on what `m()` is returning).
- Awesome diagram, for some reason this really helps put it together.

### 02 - View Function

- A small change in diction can help the motivation for this next lesson: *"...we rendered a simple, **static** message. Now, let's write a function that **dynamically** produces a message based on application state."* Something like that.
- "This is a plain JavaScript object" -> "The model is a plain JavaScript object" (just to be extra clear).
- If you decide to keep the `var vdom` change in the previous lesson: "instead of directly passing what to render" -> "instead of hardcoding our VDOM"
- Same idea to `var vdom = view(initial)`
- To prevent potential confusion, after the "It is just a simple function of the model" sentence I recommend a new sentence-paragraph saying something like "In the next lesson we will learn how to let the user increment the counter model and make the view update in response."

### 03 - Update Model

- I recommend moving the "and the function gets passed a DOM event as a parameter" detail to the below `Note:` section since it's not relevant to the current concept.
- Nice diagram again :)

### 04 - Update Function

- I recommend taking out the increase function currying. It's an elegant outcome, but it might be a roadblock for those not well-versed in fp. I think leaving it out will let the reader better focus on meosis concepts.
- Same idea with `createView`. I personally understand the purpose of the abstraction, but in the context of the tutorial, the abstraction provides no tangible benefit to the example code. It'll be more work, but I recommend omitting it here (resulting in [something like this](https://flems.io/#0=N4IgtglgJlA2CmIBcB2ArAGhAZ3ggxgC7xTIgAMALALQCuADlAIbHUBmtAdkRAPacA6AFbYQWfP2y8EZCbFhN6uUljYQEopAG1QnJmERIKNBs1YduhPoJFiQEzsUdkA9ACoA5rF4AjJrAACMDcXAB1OcJcXAOpqAIBBenpYCHwWawCJKHhw8IA3JgAnIN5swIBeAPIAbnyigLx4A0cAyqhefFpmwgEPeEIAUQRugCEATwBJKAAKUJBFejmASlqIzgLi0xZ4VoCLHn5pgthaeCWA4HCAkrLdsFK8AIBqAOPT1euwAUL4TmzC6aNboYV4QeAAd2m9zKSxW4QAvqtcut6hBuD8mLhdvsrIdzpdONctsRpk8AIxwziIurFbL4DFYyo46zTfFXALE+DTagU1bUlHFPJg8HYrgHThQh6wNmEgI-Qi0QqErTsz6zEBQCB5OYguYAYV4XGIhSQATmzxueCWGFVQXVPlohEI-B1FwC-HwKXwAGtTWj6fBMTt4bqQOTljbZWq5g6nS6xG6PV7fQE6Qzg6Gect2QBdPlIzhRAIAaVS3oChAAFmiPNh3Ww2OEvj8-vAAUDfoQQUKIZKYZS7LgCLjOJoQAAmAAcSAAzGSQCHdPpDPMkgJK4QwLA7A4nIQyAAeTV5ALQcpzBZzAB8B5cx6v4QXGCXBjICwE+GwonE-D3ZB8pRjCCsbOoSBLXGwv7sPo6hjKa2BMKO1C4IUEBsB8exQdgEAAF7wKaZI-GAfLhCB-DAY6oECCkHgbhc7KdIUUgmgE9C8GixoYfQTAwDWprjvQAAeASTkJAQCcJomCRhci8CxADEaDoGgUAAJwYX4PoeIUhp-NQskKQ2RnoeyAGFP8BFiVIKRQAEinKWpGFgEUHhoqalBCSRnBkZwSCVrweRtvRsqad62m6VA+nSHJpryfA8UJV5PkCMwhTluBASheFXCRQZsVKWgKnqQx0WGcZJlUqRlH8ClRS+v5gXFBlWU6TlUXeApKBdWgbDFZVgjEGA9Btiwio7BlzmFK5nDUABcZgPx5CeQiC45lgKScN6mg6CAeivkYkBVqh25YIq25GBuhBKEgURcPQYUfrwYAuIdlbHQAAmSAhfQAbHYhBjMNZDYPSED0Pu8I5vCQA)) and introducing the concept in a new "components" lesson, where `createView` is called to create multiple counter views.

That's all I have for now. Great job with this so far. I like meiosis and want it to succeed. I'll be back later with more feedback after you make a round of updates.

**Comment by d9k** [comment]
Awesome tutorial!

Found typo:

https://github.com/foxdonut/meiosis/blob/gh-pages/tutorial/06-scan-mithril.html#L120

> takes an accumulator function, an initial value, and a source streawm.
> streawm

**Comment by foxdonut** [comment]
@d9k thank you!

Good catch - fixed!
