### ISSUE TITLE
Redraw based on only changed data

### ISSUE THREAD

**Issue by d9k** [foxdonut/meiosis#9]
Hello!

I read your whole tutorial for mithril, awesome reading!

For example in [chapter 12](http://meiosis.js.org/tutorial/12-func-update-mithril.html):

If I add `console.log(label + ' redraw');` into `view()` function (~67th line) inside `createTemperature()` I see

```
Air redraw
Water redraw
```

every time I click any button!

Is it possible to rewrite meiosis pattern to rebuild vdom only for components dependent of changed data?

For example if I increase water temperature only `Water redraw` line must appear at console.

**Comment by foxdonut** [comment]
@d9k Greetings! Thank you for your feedback, much appreciated!

You ask a good question. This is addressed in [Chapter 3 - Update Model](http://meiosis.js.org/tutorial/03-update-model-mithril.html):

> Note: you might wonder about rebuilding the whole view and re-rendering it when something changes. Generally speaking, producing a vnode is not a performance concern. Further, re-rendering the view is what virtual-DOM libraries are good at: figuring out what minimal changes are needed to make the real DOM reflect the view.

That being said, nevertheless I will show how to prevent re-construction of sections of the virtual-DOM tree that have not changed.

I will add a link here when that section is ready. Stay tuned!

**Comment by d9k** [comment]
@foxdonut, cool! :sunglasses: :+1:

**Comment by foxdonut** [comment]
@d9k I still need to do a writeup, but in the meantime I thought you might be interested in seeing the [code example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgBMIA3AAgjYF4AOiAwAHUcIB8LAPQdOkyiDgxY1YhHoJEIAAyIAjABYQAXwrpsuHfgBWCKnQZNieJ3GLc08YgFVRbBiM3PzcABQArgFBMBTcogBOtKIAlCGS3GARaNTpgmjc3FGBjGEASvi0nDAJ5fiwaHAACkmiYYnJKXFZOSkpANz5+e6e3h4AwrRYovQuIeHUCTAxccUr8a1p-BnA+YUj3JPTswzzi8ulY37RpWuMcR2pA3vcB2XwEVCeoRU4CQDmMDCwHMhymM28DGeBV4YHCRwhLnwWFobFUaV2MMK7zgn2IyNRqnmYS2GQqGDgcFo1HarTiCJO+JRaKgJLiIOhhVMLwgcLCDMh+M4EBgAHcMS9sR8vvhhWL5pw0IT0twsPzwYz2arCVBENwKo9ack4orCfggsQEnACSy0qZOdxuTClsQIgkCji8YM0KZvcMtJ5zjEAKIMBIATwAchEsAAjGrzO4wFWY-YB7gYdSaRrzVOFbgwDjEUOW8MANQwUAiMD1ME43wySbqFKpNOEnEr1eEcTr+OIGABMCFnZgfRevqGzqHboKecKzNUepJKuBkvzHarNe4wh3WMdXTXctFetNaJTa7TjVosHqtH+YWESzQaIS3BLEeEDvzr3TC6gCqVNFzWIS1rT-P090KF0Z3CC98zVYR5G7ODvwQ5RRAwNBu23EB33DLwY3jBJEE-CgUPgh8QAgNBRAiYhkGIcNRBgfhGAAD2IABdZA4AgAAvFiACZOOQyDv3zYBuA3as9T-WURziehqNo4g9UzDQtHwQsIGLMNyxHfdyJSOCv0dMi93oeMwFoJYkyXbwOIeJZOFJLwYA44DQJtIkAEJ+FCRI608q1vKgcdvQnLCcnTINGDwgARGJExuZNtm4PMDnU7M4FzNdtOIRLGArTda3rFUm3JSlqUo6SYGw3t8H7Qdh03McYUil5oPddK1z-JdXNXMTar1HcQDXe1zO-I8T0A1Kdjg9xrxgW970fJgX24Qq6pAUzLw8bUWQAs0LRC8DJ3E7guoKB8xPnSikMoci7uEOAMKwygcK2kidsmi6KOEZS6IYpiWPYrieP4liDF0ETHtu8TJOGg7VHkzdFLQQHVIzLNNPyrbiurQz4eMsTTPMNdLJgazbJS+z3OIJy61chz8ROsCdW4PyAuc4L2ZZcL8g66LGkDJYYgAFRgaYaiCN1Uu4KAMHjf80qTc8YUynGc1COdeByMWVBPAy0t7dWLoawLqgYeKqYwPESW9C6KsqapagqBpmlaGqR1I-VzTYNgwlqvoSe-cm92oQhMMBXwMeIOBSobHqxIt5yXBtsA7a+B24KbP8zb+3lwjk7IdJy-zQmEcZP2Tv78yuv2-kBMI-3ZJ781L+ORpAAAxUS66mkc9QAWSCQh8CSbJA+RqBUcJgAqbgAE5uBkbgAFZuAAam4ABmQTuFDgf7Udv6nTr1QVFrgeG9+Gpm9b6+B6KOOE5w6u4efwokdH4hx8n58YRi46jnsmAAtHvQSaQ14r0XpvI+dcT7kXPuJJBe4UFCygtObqus+rhAGrrQoitla-UHiVbggldCkI7q-buH9xoHj3NNKSs0C7fgOPnUIp5lps1CqfdhWglorUok+DaktpYJFlksbCcliHogghdBuN065oQnrQUU-cB6qLoFAMBWA2BgN3po5+aFXqYRkSAuR-4d7CG4OI5ikjXRLG7tvGeoDXE7kEGxAAQroWxO8S6vwQX9RhJjKL4B0XogxAA2YxWjKKxjosQeg+BYzEDQKk9JYC4BYEyWgMBaJM54mwsAeg1AoAQGoAAazUlra01EgwqDCAYFIoJhAAEl9bLBUKRduz0QCJJAiktJGSRnZNyWMwpWdiAlLKRU6ptSNKNHwA0g2QIwEtLaSAG2jTtqhK-mhQZyTRnpLyeMs51FrKzJyPMmp2MlnWkjtHGAscy5bPGFHNAgJuCvPjp+duwTvyAsPvwsyFM0BWRsjAOy4QWaMxciqFmvNQqc38hsIKvC-wCx9BBf0ItXhi0YAAQXEMlEoc1r4HA4K9RW4Z7EyycfLRgEipFzTXMyhxrL6hKyJDYpAOFt7sqlpyxl7i+WCC8b4-x3AOUMrlvgTucAFE-nxVlLQuU9xwAwNURObD8ypzrOnW29tdpFBSi3DmaUADysZbAwHUOaSkEB-hoAtSyah35JJauqGwbueFuAAGJpVyRcBGMVfSBX0AFQEkB5KxU4W+oK+G35bH0scXLN+-iI3UtELStNrK3UowwBABI+bGVpD5dG7NEAaUYDpcKuVSxC2z1FDEUtDb01LH2RfPSeobV2odS2Z1rqQ16S1EjUa+4PXiXJX2219rWZOpdc2-A5Lx1DxwrY+0yCTJk2xS8A4eFoxxgTKEK4AoXBhFijAI9hEairBSnEYQobwyflPoevSW15jno1IKK9hKb2fvWEmJ9IByVvoPemIlJbv0+AvQwf9FwYBlrlpRaDCRfYgZwsW9tLLGUQY1umAA6m22DExf2XuvShptwgSOMAwz9M1a6cKtvo9RvZyqG64J1P1FUd9BxEqgKyZAcEvXasLN3Ld07b0noSKFNkcEEoxHk92-M-Hm7kXQyp6dhQ6M1BUyZNcnFVPMM4ZIOCaFqZYDiahMIMmiJanzhNciaolP3HSjPKdLmwjoccxzZz8M1R6YSH5w6AWVH3S4DZ8ShyknDNOWMxIEAsADlfR9UpNzKl3LVcs71MAtkAGVxO9OTaqSiZj3qgZwqpi6pi3oWJZPgPLbBgWFGBUfSKQsDhq1CLkjwYs1TQkyqS0I16SVtCTEN38Opy6qia5aZYfXqCYTCM27o2RqCuR6DSP8+yxCiG00xmI0I8X7VUFLOYoQ2DUhjEiQExZYA4AYN48M7TA7CH2wRv8YExDNpVLk0RNQwjnaewzDM4hZQilFM2kO3olAqDUA8vABgDC70QLoMwFgQCYBwHgCJlIlBOEYMwHQsZUThjiEcqNeZrIMDAZnLA0Bwx6i1Y0bJNReSn1p8QbJkM9QGCWFgCK+QqdoEp3FjJFT-gkEpW6KkxF4i0GovR0+GEA7UX+HqQSog2LcAABw64oYbg3bF33XhsnqAN68ADs6915sCXqfWMmYqn-AAQYnRFvA1gB977p3NkXz88N1SCpbBA027tw70+KWATUT1EYHXwuIUS8QIQKoCY8zO+qW72gU8wGe4VwGmAxeS9J9F6ugcVTr5Z9d+7-P5vC8R-t47yDUAvcBt937wWIuJcV4SDUtPrtq8u5z3ngvlvreT-XmAFvPp8iNQ7ay6+Mf-jUTAWToZWAte6ET93tA8Pzt1LwIJde6OzCcSoBUtAVTtCoGx1YPAjO-4JGgEoN05AdAkGIKIBOMgZDZFEFdwiSmBkCf0IBfygAAAEDB8AYDolQCdJwDoA7AHAQBGJmI8A4BFgIBRBXBzBLBccdAwCIDskFtsA38EgP8QAv8f9EA-8ACgC6AsAEDn9oBSCBtoDYD8BdAZB+tFsUClB0DrBlBsDcDMcCDhDJF9EMAKCqCaDf9-8aJGCQCpDAhIDdB8AT9uC5Aa1iAZBVCMBkRqIBCqAhDMDRC8DOJTAgA).

Essentially to prevent re-renders, this example:
- uses immutable objects, to easily determine a change with `!==`
- uses Mithril components to have access to lifecycle methods
- uses Mithril's `onbeforeupdate` lifecycle method to determine whether to re-render

You can see the result in the console. For example, when you change the Air temperature, you only see `render Temperature Air`, the other components are not re-rendered.

Hope that helps!

**Comment by foxdonut** [comment]
@d9k reference material:

- [Medium article regarding performance concerns](https://medium.com/@foxdonut00/addressing-performance-concerns-in-meiosis-789466cfed6b)
- [Preventing Re-renders on the Meiosis Wiki](http://meiosis.js.org/wiki/05-Lifecycle-and-other-Techniques-B-Preventing-Rerenders.html)
